* Changelog
** 2.0.1 [2019-12-21]
Thanks to [[https://github.com/E-RELevant][Erelephant]] for reporting quite a few of small bugs.

*** Improved
- App background image is scaled properly
- Color-scheme option allows you to choose between old, new, and custom colors
- Simplified the logic for message tails, bubble positions, and bubble colors
*** Fixed
- Mention's =@= symbol and contact name
- Bold font weight and audio icon color in contact's area
- Context menus for forwarded messages and messages with files
- Missing timestamp background from gif messages

** 2.0.0 [2019-12-21]
Moving forward, all the changes will be documented here.

Huge thanks to [[https://github.com/E-RELevant][Erelephant]] for testing and reporting bugs throughout this entire
process. It wouldn't have been the same without your help. :tada:

*** About v1.x.x version
*TL;DR:* It is going away soon.

When the script is done, the version 2.x.x will be compiled to =wa.user.css= file.
USo userstyle will be updated shortly after with this version.
