#!/usr/bin/env sh

# Basic tool to convert `wa.user.css` to `darkmode.css` to
# be then used with Ferdi/Franz/etc.

[ $# -eq 0 ] && {
    echo "Invalid arguments. Usage: $0 -h" >&2
    exit 1
}

help() {
    echo "\
Dark-WhatsApp helper script.

Usage:
    sh whatsapp.sh [-cfh]

Options:
    -c      Compile custom ~wa.user.styl~ userstyle.
    -f      Convert ~wa.user.css~ to ~darkmode.css~.
    -r      Remove files generated by this script.
    -h      Print help and exit.

Project repository:
    https://github.com/vednoc/dark-whatsapp
"
}

remove() {
    echo "Removing files..."

    rm darkmode.css custom.user.css
}

compile() {
    echo "Compiling..."

    temp="meta.styl"
    input="wa.user.styl"
    output="custom.user.css"

    sed -n '/@-/,$p; 1i @import("metadata.styl");' $input > $temp

    if command -v stylus >/dev/null; then
        stylus $temp -o $output
        rm $temp
    elif ! command -v npm >/dev/null; then
        echo "You're missing ~npm~ and ~Node.js~ libraries." >&2
    else
        echo "Missing ~stylus~ executable in your \$PATH." >&2
    fi
}

convert() {
    echo "Converting..."

    if [ -n "${COMPILE+x}" ]; then
        input="custom.user.css"
    else
        input="wa.user.css"
    fi

    output="darkmode.css"

    sed -n '/:root/,$p' $input | sed 's/^\ \ //; $d' > $output

    [ -e $output ] && echo "Done! $output is ready." \
                   || echo 'File not found!' >&2
}

while getopts "rcfh" option; do
    case $option in
        "r") REMOVE=1 ;;

        "c") COMPILE=1 ;;

        "f") CONVERT=1 ;;

        "h") HELP=1 ;;
    esac
done

[ -n "${HELP+x}" ] && help
[ -n "${REMOVE+x}" ] && reset
[ -n "${COMPILE+x}" ] && compile
[ -n "${CONVERT+x}" ] && convert
